### PR TITLE
Fix tar detection

### LINKED ISSUE #241: Check archive types before any other type
Thanks for the great library.

Unfortunately, I stumbled upon a very ~funny~ serious bug in our environment.

We work with archives a lot, mainly TAR archives.

If you look at the TAR archive structure you can see that it starts with an inode name.
And if you take a look at `index.js`, for instance. You can see that you check some file types before you check that it's actually an archive.

```javascript
if (check([0x42, 0x4D])) {
  return {
    ext: 'bmp',
    mime: 'image/bmp'
  };
}
```

Which means, that it might report a wrong file type if it matches any of the file type before TAR type check.

For instance, one might create a folder named *BMW*, pack it into a TAR archive and the library will report that it's a BMP image.

I'm working on a PR right now

P.S.

I wonder how come no one noticed this before :disappointed: 

[Update]

PR #242

### LINKED ISSUE #352: Tar detection seems broken
### Tar detection on MacOs seems broken

OS: MacOs 10.15.4
hardware: iMac 5k

node version: 13.13.0
file-type version: 14.2.0

I have built a couple different tarballs on various different systems, and none of them are being detected as tar files.

I've stepped through the ID process, and the headers (masked as your code indicates) are just plain old not matching, so it seems to be failing in the header matches, not in the checksum.

Below is a hexdump snippet from the two tar files that aren't being matched:

`hexdump -n 256 pest.tar
0000000 70 72 6f 63 5f 6d 6f 64 75 6c 65 2e 78 6d 6c 00
0000010 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
*
0000060 00 00 00 00 31 30 30 36 34 34 20 00 20 20 20 20
0000070 20 30 20 00 20 20 20 20 20 30 20 00 20 20 20 20
0000080 37 32 32 32 36 37 37 20 31 31 36 34 31 31 37 30
0000090 33 34 34 20 20 31 32 33 35 37 20 00 30 00 00 00
00000a0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
*
0000100`

` hexdump -n 256 orig.tar
0000000 2e 2f 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0000010 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
*
0000060 00 00 00 00 30 30 30 37 35 35 20 00 30 30 30 37
0000070 36 35 20 00 30 30 30 30 32 34 20 00 30 30 30 30
0000080 30 30 30 30 30 30 30 20 31 33 36 35 32 36 31 33
0000090 31 35 31 20 30 31 31 33 31 36 00 20 35 00 00 00
00000a0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
*
0000100`

I was curious if you could help me identify why the tar match is failing for me.

### PR DESCRIPTION
**Pull request by Borewit**
Fixes #352
Fixes #241 

Addresses issues:
* ~~Tar header was checked at a point only 256 of 512 required bytes (TAR header size) had been read.~~ Duplicate tar test, one running to early.
* Initial tar file was not identifying positive on the sample provided with issue #352.

Changes:
* Removed duplicate tar check, one at the point where 512 have been read yet. 
* Fixed initial tar signature check, allow space padding in checksum field. Fixes #352
* Updated the sum value decoding in line with [tar for Node](https://savannah.gnu.org/projects/tar)  
* Add truncated (first 512 bytes) fixture (`fixture-spaces.tar`) of sample file provided in #352.

References:
* [GNU tar project](https://savannah.gnu.org/projects/tar)
* [tar for Node](https://github.com/npm/node-tar)
* ~~[Tar signature](https://www.filesignatures.net/index.php?page=search&search=TAR&mode=EXT)~~

ToDo:
* [x] Fix tar detection
* [x] Add unit test which fails on check `check([0x30, 0x30, 0x30, 0x30, 0x30, 0x30], {offset: 148, mask: [0xF8, 0xF8, 0xF8, 0xF8, 0xF8, 0xF8]})`, by having `0x20` (space) at byte offset 148.

### CODE REVIEW

File: util.js [hunk 1]
```diff
@@ -2,14 +2,20 @@
 
 exports.stringToBytes = string => [...string].map(character => character.charCodeAt(0));
 
+function readTarSum(buffer) {
+	return parseInt(buffer.toString('utf8', 148, 154).replace(/\0.*$/, '').trim(), 8); // Read sum in header
+}
+
+exports.readTarSum = readTarSum;
```
Comment (bencmbrook) [inline util.js:9]: Does this need to be a separate util?

Can `tarHeaderCheckumMatches` simply fail early if `!isNaN(readTarSum(buffer)`?

Comment (Borewit) [reply util.js:9]: Good point.

**Comment by Borewit** [comment]
Thanks for reviewing @bencmbrook!
