### PR TITLE
Fix error when using `FileType.fromStream()` on small files

### LINKED ISSUE #341: Very small file (11 byte)
Expected - return undefined 
Bug - got exception  'End-Of-Stream'
Scenario - Sent very small file (11 bytes), the file data sent as stream.

`let fileType = await FileType.fromStream(passThroughStream)`

### PR DESCRIPTION
**Pull request by Borewit**
- Update [strtok3](https://github.com/Borewit/strtok) to [6.0.1](https://github.com/Borewit/strtok3/releases/tag/v6.0.1), fixes #341
- Add unit test revealing issue #341: test parsing short files in combination with [`FileType.fromStream`](https://github.com/sindresorhus/file-type#filetypefromstreamstream)

Note that the actual fix is implemented via a patch release in [strtok3 version 6.0.1](https://github.com/Borewit/strtok3/releases/tag/v6.0.1).

### CODE REVIEW

File: test.js [hunk 1]
```diff
@@ -1,6 +1,6 @@
 import path from 'path';
 import fs from 'fs';
-import stream from 'stream';
+import {Readable} from 'stream';
```
Comment (sindresorhus) [inline test.js:3]: `Readable` what? Named imports only makes sense when it's clear enough from the name what it is.

```suggestion
import {Readable as ReadableStream} from 'stream';
```

File: test.js [hunk 2]
```diff
@@ -484,11 +484,28 @@ test('validate the repo has all extensions and mimes in sync', t => {
...
 
+class BufferedStream extends Readable {
+	constructor(buffer) {
+		super();
+		this.push(buffer);
+		this.push(null);
+	}
+
+	_read() {
+	}
```
Comment (sindresorhus) [inline test.js:495]:
```suggestion
	_read() {}
```

**Comment by sindresorhus** [comment]
Can you give the PR a descriptive title?
